# Generated by Django 5.2.5 on 2025-10-28 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teams', models.ManyToManyField(blank=True, to='accounts.team')),
            ],
        ),
        migrations.CreateModel(
            name='BracketMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField()),
                ('home_score', models.PositiveIntegerField(blank=True, null=True)),
                ('away_score', models.PositiveIntegerField(blank=True, null=True)),
                ('played', models.BooleanField(default=False)),
                ('away', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='br_away', to='accounts.team')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='br_home', to='accounts.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bracket_matches', to='tournaments.tournament')),
            ],
        ),
    ]
